// src/utils/pdfGenerator.js

const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");

const generateApplicationPDF = async (application, outputPath) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });

    const stream = fs.createWriteStream(outputPath);
    doc.pipe(stream);

    doc.fontSize(20).text("Application Summary", { align: "center" });
    doc.moveDown();

    doc.fontSize(12).text(`Application ID: ${application._id}`);
    doc.text(`Applicant Name: ${application.applicantName}`);
    doc.text(`Sector: ${application.sector}`);
    doc.text(`State: ${application.state}`);
    doc.text(`Status: ${application.status}`);
    doc.text(`Submitted On: ${new Date(application.createdAt).toDateString()}`);

    doc.moveDown();
    doc.fontSize(16).text("Project Details");
    doc.moveDown();

    doc.fontSize(12).text(`Project Title: ${application.projectTitle}`);
    doc.text(`Description: ${application.description}`);

    doc.moveDown();
    doc.fontSize(16).text("Payment Information");
    doc.moveDown();

    if (application.payment) {
      doc.fontSize(12).text(`Amount Paid: ₹${application.payment.amount}`);
      doc.text(`Payment Status: ${application.payment.status}`);
      doc.text(`Transaction ID: ${application.payment.transactionId}`);
    } else {
      doc.fontSize(12).text("Payment not completed");
    }

    doc.moveDown();
    doc.fontSize(10).text("Generated by PARIVESH System", { align: "center" });

    doc.end();

    stream.on("finish", () => resolve(outputPath));
    stream.on("error", reject);
  });
};

const generateMoMPDF = async (meeting, outputPath) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });

    const stream = fs.createWriteStream(outputPath);
    doc.pipe(stream);

    doc.fontSize(20).text("Minutes of Meeting (MoM)", { align: "center" });
    doc.moveDown();

    doc.fontSize(12).text(`Meeting ID: ${meeting._id}`);
    doc.text(`Title: ${meeting.title}`);
    doc.text(`Date: ${new Date(meeting.date).toDateString()}`);
    doc.text(`Chairperson: ${meeting.chairperson}`);

    doc.moveDown();
    doc.fontSize(16).text("Agenda");
    doc.moveDown();

    meeting.agenda?.forEach((item, index) => {
      doc.fontSize(12).text(`${index + 1}. ${item}`);
    });

    doc.moveDown();
    doc.fontSize(16).text("Decisions");
    doc.moveDown();

    meeting.decisions?.forEach((decision, index) => {
      doc.fontSize(12).text(`${index + 1}. ${decision}`);
    });

    doc.moveDown();
    doc.fontSize(10).text("Generated by PARIVESH System", { align: "center" });

    doc.end();

    stream.on("finish", () => resolve(outputPath));
    stream.on("error", reject);
  });
};

module.exports = {
  generateApplicationPDF,
  generateMoMPDF
};